---
title: "subclusterreport"
output: html_document
---


```{r dge, eval=TRUE, echo=FALSE, results='asis'}
if(DEBUG)cat(file=stderr(), "dge\n")
if(!is.null(input$db1) & !is.null(input$db2)){
      # if (DEBUGSAVE) {
      cat(file = stderr(), "cluster: selectedCellNames: saving\n")
      save(file = "~/scShinyHubDebug/selectedCellNames.RMD.RData", list = c(ls(), ls(envir = globalenv())))
    # }

  prj = projections
  gn <- groupNames$namesDF
  
  cl1 = input$clusters1
  db1 = input$db1
  db2 = input$db2

  dge_func(projections = prj, log2cpm = log2cpm, featureData = featureData, dbCluster = prj$dbCluster, cl1 = cl1, db1 = db1, db2 = db2) 
      
  subsetData <- subset(projections, dbCluster %in% input$clusters1)
  cells.1 <- rownames(shiny::brushedPoints(subsetData, input$db1))
  cells.2 <- rownames(shiny::brushedPoints(subsetData, input$db2))
  
  subsetExpression <- log2cpm[, union(cells.1, cells.2)]
  
  genes.use <- rownames(subsetExpression)
  data.1 = apply(subsetExpression[genes.use, cells.1], 1, expMean)
  data.2 = apply(subsetExpression[genes.use, cells.2], 1, expMean)
  total.diff = (data.1 - data.2)
  
  genes.diff = names(which(abs(total.diff) > .2))
  genes.use = ainb(genes.use, genes.diff)
  
  toReturn <-
    DiffExpTest(subsetExpression, cells.1, cells.2, genes.use = genes.use)
  toReturn[, "avg_diff"] = total.diff[rownames(toReturn)]
  toReturn$Associated.Gene.Name <-
    featureData[rownames(toReturn), 'Associated.Gene.Name']
  selectedDge <- toReturn
  cat(stderr(), rownames(toReturn)[1:5])
  
  dge <-     toReturn
  # print(knitr::kable(dge))
  shiny::renderTable(dge)
  if(DEBUG)cat(file=stderr(), "dge:done11\n")
}else{
  dge=NA
}
```


```{r selectedDge, eval=FALSE}

```
