---
title: "PostAnalysis.specialPlots.Rmd"
author: "Bernd Jagla"
date: "11/28/2018"
output: html_document
---

```{r, echo=FALSE}
  cat(file = stderr(), getwd())

  require(shiny)
  require(plotly)
  require(shinythemes)
  require(ggplot2)
  require(DT)
  require(pheatmap)
  require(threejs)
  require(sm)
  require(RColorBrewer)
  require(mclust)
  require(reshape)
  # require(cellrangerRkit)
  # require(SCORPIUS)
  require(ggplot2)
  require(knitr)
  require(kableExtra)
  require(shinyWidgets)
  require(scater)

  source("serverFunctions.R")
  source("reactives.R", local = TRUE)

```



```{r loadRDS, include=FALSE}

projectPath = "~/Desktop/"




```

```{r}
load(file = paste0(projectPath, "/sessionData.RData"))
input = myparams

```

```{r}
heatmapFile = 'hucellsenescence.png'
genesin <- c("h2afx,cdkn2a,cdkn1a")

```


```{r heatmap}

scEx_matrix <- as.matrix(assays(scEx_log)[[1]])
# genesin <- c("h2afx,cdkn2a,cdkn1a")

genesin2 <- geneName2Index(genesin, featuredata)
genesin = (paste0(featuredata[genesin2[which (genesin2 %in% rownames(scEx_matrix) )],"Associated.Gene.Name"], collapse =",", sep=""))

heatmapData <- coE_heatmapFunc(
  featureData = featuredata, scEx_matrix = scEx_matrix,
  projections = projections, genesin = genesin, cells = colnames(scEx_matrix)
)
addColNames <- input$"coExpHeatmapModule-ColNames"
orderColNames <- input$"coExpHeatmapModule-orderNames"
moreOptions <- input$"coExpHeatmapModule-moreOptions"

addColNames = "sampleNames"
orderColNames = "sampleNames"
moreOptions = TRUE
proje <- projections

heatmapData$filename <- paste0(projectPath,"/", heatmapFile)

if (is.null(moreOptions)) moreOptions <- FALSE

if (length(addColNames) > 0 & moreOptions) {
  heatmapData$annotation_col <- proje[rownames(heatmapData$annotation_col), addColNames, drop = FALSE]
}
if (sum(orderColNames %in% colnames(proje)) > 0 & moreOptions) {
  heatmapData$cluster_cols <- FALSE
  heatmapData$mat <- heatmapData$mat[, rownames(psych::dfOrder(proje, orderColNames)), drop = FALSE]
}

do.call(pheatmap, heatmapData)

```


```{r violinPlot}
  featureData <- featuredata
  # geneListStr <- input$geneGrpVioIds
  geneListStr = genesin
  projectionVar <- input$dimension_xVioiGrp
  minExpr <- input$coEminExpr

  retVal <- geneGrp_vioFunc(
    genesin = geneListStr,
    projections = proje,
    scEx = scEx,
    featureData = featureData,
    minExpr = minExpr,
    dbCluster = projectionVar
  )
  retVal
  
  genesin = geneListStr
  genesin <- toupper(genesin)
  genesin <- gsub(" ", "", genesin, fixed = TRUE)
  genesin <- strsplit(genesin, ",")

    map <-
    rownames(featureData[which(featureData$Associated.Gene.Name %in% genesin[[1]]), ])
expression <- Matrix::colSums(assays(scEx_log)[[1]][map, ] >= minExpr)
  

ttt=t(as.matrix(assays(scEx_log)[[1]][map, ]))
```






