---
title: "child report"
output: html_document
---

## Scater Plot

```{r bj-gQC-setup, echo=FALSE, warning=FALSE, message=FALSE, error=FALSE}
if(exists("params")){
  cat(file=stderr(), paste("Scater Plot report\n"))
}else{
  rm(list = ls())
  load("~/scShinyHubDebug/report.RData")
  cat(file=stderr(), getwd())
  
  require(shiny)
  require(plotly)
  require(shinythemes)
  require(ggplot2)
  require(DT)
  require(pheatmap)
  require(threejs)
  require(sm)
  require(RColorBrewer)
  require(mclust)
  require(reshape)
  require(cellrangerRkit)
  require(SCORPIUS)
  require(ggplot2)
  require(knitr)
  require(kableExtra)
  require(shinyWidgets)
  require(scater)
  
  source("../../../serverFunctions.R")
  source("../../../privatePlotFunctions.R")
  source("../../../reactives.R", local = TRUE)
  source("reactives.R", local = TRUE)
  
  LOCALEXECUTION = TRUE # to know that we are debugging.
  useCells = useCellsFunc(dataTables, minG = input$minGenes, maxG = input$maxGenes, geneNames = input$minExpGenes)
  ipIDs = input$selectIds
  geneListSelection = input$geneListSelection
  minGene <- input$minGenesGS
  
  useGenes = useGenesFunc(dataTables, useCells, ipIDs, geneListSelection, minGene)
  featureDataReact = dataTables$featuredata[useGenes, ]
  featureData = dataTables$featuredata[useGenes, ]
  gbm = dataTables$gbm[useGenes, useCells]
  gbm_log = dataTables$gbm_log[useGenes, useCells]
  log2cpm = dataTables$log2cpm[useGenes, useCells]
  if(DEBUG)cat(file=stderr(), "pca\n")
  
  pca = pcaFunc(gbm_log)
  if(DEBUG)cat(file=stderr(), "tsne\n")
  seed=1
  set.seed(seed = seed)
  tsne = run_tsne(pca, dims = 3, perplexity = 30, theta = 0.5)
  if(DEBUG)cat(file=stderr(), "tsne: done\n")
  if(DEBUG)cat(file=stderr(), "tsne.data\n")
  
  if(DEBUG)cat(file=stderr(), "kmClustering\n")
  clustering=list()
  
  kNr = 10
  for(kNr in 2:10) {
    set.seed(seed = seed)
    km = run_kmeans_clustering(pca, k=kNr)
    clustering[[paste0("kmeans_",kNr,"_clusters")]] = data.frame("Barcode" = rownames(data.frame(km$cluster)), "Cluster" = km$cluster)
  }
  
  kmClustering = clustering
  if(DEBUG)cat(file=stderr(), "kmClustering:done\n")
  
  
  tsne.data = data.frame(tsne$Y)
  colnames(tsne.data) = c("tsne1", "tsne2", "tsne3")
  tsne.data$dbCluster = clustering$kmeans_10_clusters$Cluster-1
  rownames(tsne.data) = clustering$kmeans_10_clusters$Barcode
  if(DEBUG)cat(file=stderr(), "tsne.data: done\n")
  
}

cat(file=stderr(),paste(ls(),collapse = "\n"))
  cat(file=stderr(), paste("\nmy Scater Plot report\n"))
cat(file=stderr(),paste("bj-gQC-tsne3d: ", class(tsne.data)))
  
```




```{r bj-gQC-tsne3d, eval=TRUE, echo=FALSE}
cat(file=stderr(),paste("bj-gQC-tsne3d: ", class(tsne.data)))
  
  tsne.data <- as.data.frame(tsne.data)
  cat(file=stderr(),colnames(tsne.data)[1:5])
  tsne.data$dbCluster <- as.factor(tsne.data$dbCluster)
  
  p <-
    plot_ly(
      tsne.data,
      x = ~ tsne1,
      y = ~ tsne2,
      z = ~ tsne3,
      type = "scatter3d",
      color =  ~ dbCluster,
      hoverinfo = "text",
      text = paste('Cluster:', as.numeric(as.character(tsne.data$dbCluster))),
      mode = 'markers',
      marker =
        list(
          line = list(width = 0),
          size = rep(10, nrow(tsne.data)),
          sizeref = 3
        )
    )
  if(DEBUG)cat(file=stderr(), "output$tsne_main: done\n")
  layout(p)
  


```

```{r plotUmiHist, eval=TRUE, echo=FALSE}

hist(colSums(as.matrix(exprs(gbm))), breaks = 50, main="histogram of number of UMI per cell")
```


```{r variancePCA, eval=TRUE, echo=FALSE}
if(exists("pca$var_pcs")){
  barplot(pca$var_pcs, main="Variance captured by first PCs")
}
```

## Histogram of samples


```{r histSamples}
if(DEBUGSAVE) 
  save(file = "~/scShinyHubDebug/histSamples.RData", list = c(ls(),ls(envir = globalenv())))
sampleInf <- sampleInfoFunc(gbm)
sampleHistFunc(sampleInf)
```

