---
title: "child report"
output: html_document
---

## Scater Plot

```{r bj-DE-setup, echo=FALSE, warning=FALSE}
if(exists("params")){
  cat(file=stderr(), paste("Scater Plot report\n"))
}else{
  rm(list = ls())
  load("~/scShinyHubDebug/report.RData")
  cat(file=stderr(), getwd())
  
  require(shiny)
  require(plotly)
  require(shinythemes)
  require(ggplot2)
  require(DT)
  require(pheatmap)
  require(threejs)
  require(sm)
  require(RColorBrewer)
  require(mclust)
  require(reshape)
  require(cellrangerRkit)
  require(SCORPIUS)
  require(ggplot2)
  require(knitr)
  require(kableExtra)
  require(shinyWidgets)
  require(scater)
  
  source("../../../serverFunctions.R")
  source("../../../privatePlotFunctions.R")
  source("../../../reactives.R", local = TRUE)
  # source("reactives.R", local = TRUE)
  
  LOCALEXECUTION = TRUE # to know that we are debugging.
  useCells = useCellsFunc(dataTables, minG = input$minGenes, maxG = input$maxGenes, geneNames = input$minExpGenes)
  ipIDs = input$selectIds
  geneListSelection = input$geneListSelection
  minGene <- input$minGenesGS
  
  useGenes = useGenesFunc(dataTables, useCells, ipIDs, geneListSelection, minGene)
  featureDataReact = dataTables$featuredata[useGenes, ]
  featureData = dataTables$featuredata[useGenes, ]
  gbm = dataTables$gbm[useGenes, useCells]
  gbm_log = dataTables$gbm_log[useGenes, useCells]
  log2cpm = dataTables$log2cpm[useGenes, useCells]
  
}
```

```{r bj-DE-scater, eval=FALSE }
cat(file=stderr(),paste(class(gbm_log),collapse = "\n"))
scaterReads = scaterReadsFunc(gbm, gbm_log, featureDataReact)
scater::plotQC(scaterReads, type = "highest-expression", col_by_variable="fixed")

```


# Expression ------------------------------------------------------------------
expCluster <- callModule(clusterServer, "expclusters", tsne.data, reactive(input$gene_id))




# EXPLORE TAB VIOLIN PLOT ------------------------------------------------------------------
# TODO module for violin plot  ??
output$gene_vio_plot <- renderPlot({


```{r gene_vio_plot, eval=TRUE}
if(DEBUG)cat(file=stderr(), "output$gene_vio_plot\n")

geneid <- rownames(featureData[which(featureData$Associated.Gene.Name ==
                                       toupper(input$gene_id)), ])[1]

expression <- log2cpm[geneid, ]

validate(need(is.na(sum(expression)) != TRUE, ''))

tsneData <- cbind(tsne.data, t(expression))
names(tsneData)[names(tsneData) == geneid] <- 'values'
#tsne.data<-subset(tsne.data,dbCluster!=0)

p1 <-
  ggplot(tsneData, aes(factor(dbCluster), values, fill = factor(dbCluster))) +
  geom_violin(scale = "width") +
  stat_summary(
    fun.y = median,
    geom = "point",
    size = 5,
    color = 'black'
  ) +
  stat_summary(fun.data = n_fun, geom = "text") +
  theme_bw() +
  theme(
    axis.text.x = element_text(
      angle = 90,
      size = 12,
      vjust = 0.5
    ),
    axis.text.y = element_text(size = 12),
    strip.text.x = element_text(size = 16),
    strip.text.y = element_text(size = 14),
    axis.title.x = element_text(face = "bold", size = 16),
    axis.title.y = element_text(face = "bold", size = 16),
    legend.position = "none"
  ) +
  xlab('Cluster') +
  ylab('Expression') +
  ggtitle(toupper(input$gene_id))
if(DEBUG)cat(file=stderr(), "output$gene_vio_plot:done\n")
p1

```


output$panelPlot <- renderPlot({


```{r panelPlot, eval=TRUE}
if(DEBUG)cat(file=stderr(), "output$panelPlot\n")

genesin <- input$panelplotids
genesin <- toupper(genesin)
genesin <- gsub(" ", "", genesin, fixed = TRUE)
genesin <- strsplit(genesin, ',')
genesin<-genesin[[1]]

par(mfrow=c(ceiling(length(genesin)/4),4), mai = c(0, 0., 0., 0.))
rbPal <- colorRampPalette(c('#f0f0f0','red'))

if (input$clusters4 == 'All') 
{
  for (i in 1:length(genesin)){
    Col <- rbPal(10)[
      as.numeric(
        cut(
          as.numeric(
            log2cpm[
              rownames(featureData[which(featureData$Associated.Gene.Name==genesin[i]),])
              ,]
          ),breaks = 10))]
    plot(tsne.data[,input$dimension_x4],tsne.data[,input$dimension_y4],col=Col,pch=16,axes = FALSE,frame.plot = TRUE, ann=FALSE)
    title(genesin[i],line=-1.2,adj = 0.05,cex.main=2)
  }
}else{
  for (i in 1:length(genesin)){
    
    subsetTSNE <- subset(tsne.data, dbCluster == input$clusters4)
    
    Col <- rbPal(10)[
      as.numeric(
        cut(
          as.numeric(
            log2cpm[
              rownames(featureData[which(featureData$Associated.Gene.Name==genesin[i]),])
              ,]
          ),breaks = 10))]
    
    names(Col)<-rownames(tsne.data)
    plotCol<-Col[rownames(subsetTSNE)]
    plot(subsetTSNE[,input$dimension_x4],subsetTSNE[,input$dimension_y4],col=plotCol,pch=16,axes = FALSE,frame.plot = TRUE, ann=FALSE)
    title(genesin[i],line=-1.2,adj = 0.05,cex.main=2)
    
  }
}

```



output$tsne_plt <- renderPlotly({

```{r bj-DE-tsne_plt, eval=TRUE}
if(DEBUG)cat(file=stderr(), "output$tsne_plt\n")
geneid <- rownames(featureData[which(featureData$Associated.Gene.Name ==
                                       toupper(input$gene_id)), ])[1]

expression <- log2cpm[geneid, ]

tsneData <- cbind(tsne.data, t(expression))
names(tsneData)[names(tsneData) == geneid] <- 'values'

p <-
  plot_ly(
    tsneData,
    x = ~ tsne1,
    y = ~ tsne2,
    z = ~ tsne3,
    type = "scatter3d",
    hoverinfo = "text",
    text = paste('Cluster:', as.numeric(as.character(tsne.data$dbCluster))),
    mode = 'markers',
    marker = list(
      size = 2,
      line = list(width = 0),
      color =  ~ values,
      colors = 'Greens'
    )
  )
layout(p, title = toupper(input$gene_id))

```


```{r bj-coExp-panelPlot, eval=TRUE}
if(DEBUG)cat(file=stderr(), "output$panelPlot\n")

genesin <- input$panelplotids
genesin <- toupper(genesin)
genesin <- gsub(" ", "", genesin, fixed = TRUE)
genesin <- strsplit(genesin, ',')
genesin<-genesin[[1]]

par(mfrow=c(ceiling(length(genesin)/4),4), mai = c(0, 0., 0., 0.))
rbPal <- colorRampPalette(c('#f0f0f0','red'))

if (input$clusters4 == 'All') 
{
  for (i in 1:length(genesin)){
    Col <- rbPal(10)[
      as.numeric(
        cut(
          as.numeric(
            log2cpm[
              rownames(featureData[which(featureData$Associated.Gene.Name==genesin[i]),])
              ,]
          ),breaks = 10))]
    plot(tsne.data[,input$dimension_x4],tsne.data[,input$dimension_y4],col=Col,pch=16,axes = FALSE,frame.plot = TRUE, ann=FALSE)
    title(genesin[i],line=-1.2,adj = 0.05,cex.main=2)
  }
}else{
  for (i in 1:length(genesin)){
    
    subsetTSNE <- subset(tsne.data, dbCluster == input$clusters4)
    
    Col <- rbPal(10)[
      as.numeric(
        cut(
          as.numeric(
            log2cpm[
              rownames(featureData[which(featureData$Associated.Gene.Name==genesin[i]),])
              ,]
          ),breaks = 10))]
    
    names(Col)<-rownames(tsne.data)
    plotCol<-Col[rownames(subsetTSNE)]
    plot(subsetTSNE[,input$dimension_x4],subsetTSNE[,input$dimension_y4],col=plotCol,pch=16,axes = FALSE,frame.plot = TRUE, ann=FALSE)
    title(genesin[i],line=-1.2,adj = 0.05,cex.main=2)
    
  }
}

```

